nginx:
    image: nginx:latest
    volumes:
        - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/var/www/html
    ports:
        - "80:80"
    links:
        - php
php:
    command: php-fpm --allow-to-run-as-root
    build: ./conf
    ports:
        - 9000
    links:
        - mysql
    volumes:
        - .:/var/www/html
        - ./conf/php.ini:/usr/local/etc/php/php.ini
    environment:
        MYSQL_DATABASE: myapp
mysql:
    image: mariadb
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: myapp
